In [50]:
import pandas as pd 
import datetime

df = pd.read_csv("C:\\Users\I321734\Downloads\phd\PhDData\hh101\hh101.rawdata.txt", header = None, sep='\t', names = ['Time', 'ID', 'Object', 'Room', 'Status', 'Sensor'])
df['Time'] = pd.to_datetime(df['Time'])

df['Time'] = df['Time'].apply(lambda x: x.strftime('%Y-%m-%d %H:%M:%S.%f')[:-3])

In [51]:
df.head()
df.ID.unique()

array(['D001', 'D002', 'T102', 'BATP102', 'T103', 'BATP103', 'T101',
       'MA016', 'D003', 'M009', 'LS010', 'BATP010', 'M010', 'LS011',
       'BATP011', 'M007', 'LS008', 'BATP008', 'M008', 'LS009', 'BATP009',
       'M011', 'LS012', 'BATP012', 'LS001', 'BATP001', 'LS002', 'BATP002',
       'M001', 'LS016', 'BATP016', 'T105', 'T104', 'LS003', 'BATP003',
       'M002', 'LS004', 'BATP004', 'M003', 'LS005', 'BATP005', 'M004',
       'LS006', 'BATP006', 'M005', 'LS007', 'BATP007', 'MA013', 'LS013',
       'BATP013', 'M012', 'MA015', 'LS015', 'BATP015', 'MA014', 'LS014',
       'BATP014', 'M006'], dtype=object)

Bedroom
    M009 = 7JIR6ss5JgCcA6Dh8Rss6F - wardrobe(room)
    LS009 = 3Ge72Lb61T2Yrrnj7rHKN0 - light
    M012 = 469QMe9ZvU3LiZwmc4mmIH - bed
    LS012 = 2QpbQO34UZeLqX2DMfFNvt - bedlight
    MA014 = 5dbdQuWDpqllJrxRaAUOY0 - bed
    LS014 = 5CmUIV8qwRLknv6rgc5a7t - bedlight
    M011 = 6wGPPCsFe50E8HAtZFd6PV - bedroom hall
    LS011 = 71W6rKSdOXRuJTG8eYmO27 - bedroom hall light
Bathroom
    D003 = 4uAQxNoZe3Vl3wEl5VAJI1 - bathroom door
    T103 = 2cCL4CyTHQ3hXU1AUigzsM - bathroom temperature
    MA015 = 3BH9cQy0jeVGBjxwEli08W - bathroom
    LS015 = 3tqYOfEXDrOHkbGPFGK6Db - bathrom light
Kitchen
    MA016 =  - Kitchen
    LS016 =  - Kitchen Light
    M003 = 4St4Yt8Un6gIcqc7nlqTaw - Kitchen
    LS003 = 27kTFz7Lq4xpKHNFMsuSgT
    M006 = 6zknLOyttl8U3KZ6FstT6j - Refrigerator
    LS006 = - Refrigerator
    M007 = 5Kcixoulb3F5WZO138ZSsP - Freezer
    LS007 = - Freezer Light
    M002 = 48MdsLttbFFpwbxoSklpdf - Kitchen next to fridge
    LS002 = 6TcIAFzYSgpwcByD2CFMY5 
LIving Room
    M010 =  - Living Room Hall
    LS010 =  - Living Room Hall Light
    T104 = 6c75BdS3uCex0b54c93KC0 - Living Room Temperature
    T105 =  - Living Room Temperature
    M005 = 2jwKpZTH3bGalcijQMfNx6 - Living Room
    LS005 = 4qV5f8jcBDVtvPBty2NYtD - Living Room Light
    MA013 = 4qG5cQjapj0Nk8ILvzpwxY - TV stand
    LS013 = 6ntn0fnLClzMGcVZswMWRb - Light next to TV
    M008 = 7ABw8PRwiapJmyBau9gqcw - Living Room Couch
    LS008 = 38Z88xbdQh1MutZupTgrus - Living Room Couch light
    M004 = 7NoTTuUTzZC40TX9JQ0n4V - Dining room Chair
    LS004 = 5DBHIfps52IPRa8EirsD6x - Dining room Light   
Entryway
    M001 = 60KSSlEeCt1MYV5DEoigXg - Outside door motion sensor
    LS001 = 3NtIg6iWXBnRlPLVouPyO6 - Light entryway
    T102 = 7P6GpxIomHcfKP1MZpdI3q - Front Door Temperature
    D002 = 6XGGRHclhMK3ifriUqShfN - Outside Door

In [52]:
#Entryway
frontDoor = '6XGGRHclhMK3ifriUqShfN' #D002
frontDoor_temperature = '7P6GpxIomHcfKP1MZpdI3q' #T102 + BATP102
frontDoor_motionSensor = '60KSSlEeCt1MYV5DEoigXg' #M001
entrywayLight = '3NtIg6iWXBnRlPLVouPyO6' #LS001 + BATP001

#LivingRoom
livingRoom_temperature = '6c75BdS3uCex0b54c93KC0' #T104 + BATP104
livingRoom_motionSensor = '2jwKpZTH3bGalcijQMfNx6'  #M005 
livingRoom_light = '4qV5f8jcBDVtvPBty2NYtD' # LS005 + BATP005
TV_stand = '4qG5cQjapj0Nk8ILvzpwxY'   #MA013 
TV_light = '6ntn0fnLClzMGcVZswMWRb'   #LS013  + BATP013
livingRoom_couch = '7ABw8PRwiapJmyBau9gqcw' #   M008 
livingRoom_couchLight = '38Z88xbdQh1MutZupTgrus'  #LS008 + BATP008
diningRoom_chair = '7NoTTuUTzZC40TX9JQ0n4V' #M004  
diningRoom_light = '5DBHIfps52IPRa8EirsD6x' #LS004 + BATP004  

#Kitchen
kitchen_motionSensor = '4St4Yt8Un6gIcqc7nlqTaw' #M003 
kitchen_light = '27kTFz7Lq4xpKHNFMsuSgT' #  LS003 + BATP003
refrigerator = '6zknLOyttl8U3KZ6FstT6j'  #M006 + LS006 + BATP006
freezer = '5Kcixoulb3F5WZO138ZSsP' #   M007 + LS007 + BATP007
refrigerator_motionSensor = '48MdsLttbFFpwbxoSklpdf' #M002 =  - Kitchen next to fridge
refrigerator_light = '6TcIAFzYSgpwcByD2CFMY5' #LS002 + BATP002

#Bedroom
bedroom_wardrobe = '7JIR6ss5JgCcA6Dh8Rss6F' #M009
bedroom_wardrobeLight = '3Ge72Lb61T2Yrrnj7rHKN0' #   LS009 + BATP009
bedroom_bed = '469QMe9ZvU3LiZwmc4mmIH' #   M012 =  - bed
bedroom_bedLight = '2QpbQO34UZeLqX2DMfFNvt'    #LS012 + BATP012
bedroom_bed2 = '5dbdQuWDpqllJrxRaAUOY0' #MA014 =  - bed
bedroom_bedLight2 = '5CmUIV8qwRLknv6rgc5a7t'  #LS014 +BATP014
bedroom_hallPresence = '6wGPPCsFe50E8HAtZFd6PV' #M011 =  - bedroom hall
bedroom_hallLight = '71W6rKSdOXRuJTG8eYmO27' #LS011 + BATP011

#Bathroom
bathroom_door = '4uAQxNoZe3Vl3wEl5VAJI1' #D003 =  - bathroom door
bathroom_temperature = '2cCL4CyTHQ3hXU1AUigzsM' #T103 + BATP103
bathroom_motionSensor = '3BH9cQy0jeVGBjxwEli08W' #MA015
bathroom_light = '3tqYOfEXDrOHkbGPFGK6Db' #LS015 + BATP015

In [53]:
indexx = df[(df.ID == 'D001') | (df.ID == 'T101') | (df.ID == 'MA016') | (df.ID == 'LS010') | (df.ID == 'BATP010') | (df.ID == 'M010') | (df.ID == 'LS016') | (df.ID == 'BATP016') | (df.ID == 'T105')].index
df = df.drop(indexx)
df.ID.unique()

array(['D002', 'T102', 'BATP102', 'T103', 'BATP103', 'D003', 'M009',
       'LS011', 'BATP011', 'M007', 'LS008', 'BATP008', 'M008', 'LS009',
       'BATP009', 'M011', 'LS012', 'BATP012', 'LS001', 'BATP001', 'LS002',
       'BATP002', 'M001', 'T104', 'LS003', 'BATP003', 'M002', 'LS004',
       'BATP004', 'M003', 'LS005', 'BATP005', 'M004', 'LS006', 'BATP006',
       'M005', 'LS007', 'BATP007', 'MA013', 'LS013', 'BATP013', 'M012',
       'MA015', 'LS015', 'BATP015', 'MA014', 'LS014', 'BATP014', 'M006'],
      dtype=object)

In [54]:
df1 = df
df1['entity_id'] = df1['ID']

df1['ID'] = df1['ID'].replace(['D002', 'T102', 'BATP102', 'T103', 'BATP103', 'D003', 'M009',
       'LS011', 'BATP011', 'M007', 'LS008', 'BATP008', 'M008', 'LS009',
       'BATP009', 'M011', 'LS012', 'BATP012', 'LS001', 'BATP001', 'LS002',
       'BATP002', 'M001', 'T104', 'LS003', 'BATP003', 'M002', 'LS004',
       'BATP004', 'M003', 'LS005', 'BATP005', 'M004', 'LS006', 'BATP006',
       'M005', 'LS007', 'BATP007', 'MA013', 'LS013', 'BATP013', 'M012',
       'MA015', 'LS015', 'BATP015', 'MA014', 'LS014', 'BATP014', 'M006'],
       ['position', 'temperature', 'battery', 'temperature', 'battery', 'position', 'presence',
       'brightness', 'battery', 'position', 'brightness', 'battery', 'position', 'brightness',
       'battery', 'presence', 'brightness', 'battery','brightness', 'battery','brightness',
       'battery', 'presence', 'temperature', 'brightness', 'battery', 'presence','brightness',
       'battery', 'presence', 'brightness', 'battery','presence', 'brightness', 'battery',
       'presence', 'brightness', 'battery', 'presence', 'brightness', 'battery', 'presence',
       'presence', 'brightness', 'battery', 'presence', 'brightness', 'battery', 'presence'])
df1['entity_id'] = df1['entity_id'].replace(['D002', 'T102', 'BATP102', 'T103', 'BATP103', 'D003', 'M009',
       'LS011', 'BATP011', 'M007', 'LS008', 'BATP008', 'M008', 'LS009',
       'BATP009', 'M011', 'LS012', 'BATP012', 'LS001', 'BATP001', 'LS002',
       'BATP002', 'M001', 'T104', 'LS003', 'BATP003', 'M002', 'LS004',
       'BATP004', 'M003', 'LS005', 'BATP005', 'M004', 'LS006', 'BATP006',
       'M005', 'LS007', 'BATP007', 'MA013', 'LS013', 'BATP013', 'M012',
       'MA015', 'LS015', 'BATP015', 'MA014', 'LS014', 'BATP014', 'M006'],
       [frontDoor, frontDoor_temperature, frontDoor_temperature, bathroom_temperature, bathroom_temperature, bathroom_door, bedroom_wardrobe, 
       bedroom_hallLight, bedroom_hallLight, freezer, livingRoom_couchLight, livingRoom_couchLight, livingRoom_couch, bedroom_wardrobeLight,
       bedroom_wardrobeLight, bedroom_hallPresence, bedroom_bedLight, bedroom_bedLight, entrywayLight, entrywayLight, refrigerator_light,
       refrigerator_light, frontDoor_motionSensor, livingRoom_temperature, kitchen_light, kitchen_light, refrigerator_motionSensor, diningRoom_light,
       diningRoom_light, kitchen_motionSensor, livingRoom_light, livingRoom_light, diningRoom_chair, refrigerator, refrigerator,
       livingRoom_motionSensor, freezer, freezer, TV_stand, TV_light, TV_light, bedroom_bed,
       bathroom_motionSensor, bathroom_light, bathroom_light, bedroom_bed2, bedroom_bedLight2, bedroom_bedLight2, refrigerator])
df1=df1.replace(['OPEN', 'ON'], 'true')
df1=df1.replace(['CLOSE', 'OFF'], 'false')
df1.head()

,Time,ID,Object,Room,Status,Sensor,entity_id
1,2012-07-18 12:54:45.196,position,OutsideDoor,FrontDoor,true,Control4-Door,6XGGRHclhMK3ifriUqShfN
2,2012-07-18 12:54:45.247,temperature,Ignore,FrontDoorTemp,78,Control4-Temperature,7P6GpxIomHcfKP1MZpdI3q
3,2012-07-18 12:54:45.302,battery,Ignore,Ignore,85,Control4-BatteryPercent,7P6GpxIomHcfKP1MZpdI3q
4,2012-07-18 12:54:45.399,temperature,Ignore,BathroomTemp,25,Control4-Temperature,2cCL4CyTHQ3hXU1AUigzsM
5,2012-07-18 12:54:45.472,battery,Ignore,Ignore,82,Control4-BatteryPercent,2cCL4CyTHQ3hXU1AUigzsM

In [55]:
df = df1
import datetime
df['Time'] = pd.to_datetime(df['Time'])
df['Time'] = df['Time'].apply(lambda x: x.replace(year=2021))
df.head()

,Time,ID,Object,Room,Status,Sensor,entity_id
1,2021-07-18 12:54:45.196,position,OutsideDoor,FrontDoor,true,Control4-Door,6XGGRHclhMK3ifriUqShfN
2,2021-07-18 12:54:45.247,temperature,Ignore,FrontDoorTemp,78,Control4-Temperature,7P6GpxIomHcfKP1MZpdI3q
3,2021-07-18 12:54:45.302,battery,Ignore,Ignore,85,Control4-BatteryPercent,7P6GpxIomHcfKP1MZpdI3q
4,2021-07-18 12:54:45.399,temperature,Ignore,BathroomTemp,25,Control4-Temperature,2cCL4CyTHQ3hXU1AUigzsM
5,2021-07-18 12:54:45.472,battery,Ignore,Ignore,82,Control4-BatteryPercent,2cCL4CyTHQ3hXU1AUigzsM

In [56]:
df=df.rename(columns={"Time": "timestamp", "ID": "attribute_name", "Status": "value"})
df = df.drop(['Object', 'Room', 'Sensor'], axis=1)
df = df.reset_index()
df = df.drop(['index'], axis=1)
df = df[['timestamp', 'entity_id', 'attribute_name', 'value']]
df.to_csv("C:\\Users\I321734\Downloads\phd\PhDData\hh101\hh101.csv", index = False, header = False)

In [57]:
df.head()

                timestamp               entity_id attribute_name value
0 2021-07-18 12:54:45.196  6XGGRHclhMK3ifriUqShfN       position  true
1 2021-07-18 12:54:45.247  7P6GpxIomHcfKP1MZpdI3q    temperature    78
2 2021-07-18 12:54:45.302  7P6GpxIomHcfKP1MZpdI3q        battery    85
3 2021-07-18 12:54:45.399  2cCL4CyTHQ3hXU1AUigzsM    temperature    25
4 2021-07-18 12:54:45.472  2cCL4CyTHQ3hXU1AUigzsM        battery    82